[package]
name = "termimad"
version = "0.8.17"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/termimad"
description = "Markdown Renderer for the Terminal"
edition = "2018"
keywords = ["markdown", "terminal", "tui", "renderer", "parser"]
license = "MIT"
categories = ["command-line-interface", "text-processing", "template-engine"]
readme = "README.md"

[dependencies]
lazy_static = "1.4"
minimad = "=0.6.4"
crossterm = "0.16.0"
crossbeam = "0.7"
thiserror = "1.0.4"

[features]
special-renders = []
default = ["special-renders"]

[patch.crates-io]
# minimad = { path = "../minimad" }
# crossterm = { path = "../crossterm-rs/crossterm" }
