[package]
name = "termimad"
version = "0.6.4"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/termimad"
description = "Markdown Renderer for the Terminal"
edition = "2018"
keywords = ["markdown", "terminal", "tui", "renderer", "parser"]
license = "MIT"
categories = ["command-line-interface", "text-processing"]
readme = "README.md"

[dependencies]
lazy_static = "1.3.0"
minimad = "0.4.1"
#minimad = { path = "../minimad" }
crossterm_cursor = "0.2.6"
crossterm_input = "0.3.9"
crossterm_screen = "0.2.5"
crossterm_style = "0.4.1"
crossterm_terminal = "0.2.6"
crossterm_utils = "0.2.4"
crossbeam = "0.7.2"
