[package]
name = "termimad"
version = "0.8.1"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/termimad"
description = "Markdown Renderer for the Terminal"
edition = "2018"
keywords = ["markdown", "terminal", "tui", "renderer", "parser"]
license = "MIT"
categories = ["command-line-interface", "text-processing"]
readme = "README.md"

[dependencies]
lazy_static = "1.4"
minimad = "0.5.1"
crossterm = "0.13.2"
crossbeam = "0.7"
thiserror = "1.0.4"

[patch.crates-io]
# minimad = { path = "../minimad" }
# crossterm = { path = "../crossterm-rs/crossterm" }
