[package]
name = "termimad"
version = "0.14.2"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/termimad"
description = "Markdown Renderer for the Terminal"
edition = "2018"
keywords = ["markdown", "terminal", "tui", "renderer", "parser"]
license = "MIT"
categories = ["command-line-interface", "text-processing", "template-engine"]
readme = "README.md"

[dependencies]
minimad = "0.8.0"
crossterm = "0.20.0"
crossbeam = "0.8"
thiserror = "1.0"
unicode-width = "0.1.8"

[features]
special-renders = []
default = ["special-renders"]

[patch.crates-io]
# minimad = { path = "../minimad" }
# crossterm = { path = "../crossterm-rs/crossterm" }
