[package]
name = "termimad"
version = "0.6.4"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/termimad"
description = "Markdown Renderer for the Terminal"
edition = "2018"
keywords = ["markdown", "terminal", "tui", "renderer", "parser"]
license = "MIT"
categories = ["command-line-interface", "text-processing"]
readme = "README.md"

[dependencies]
lazy_static = "1.3"
minimad = "0.4.1"
#minimad = { path = "../minimad" }
crossterm_cursor = "=0.2.4"
crossterm_input = "=0.3.6"
crossterm_screen = "=0.2.3"
crossterm_style = "=0.3.3"
crossterm_terminal = "=0.2.4"
crossterm_utils = "=0.2.3"
crossbeam = "0.7"
