[package]
name = "termimad"
version = "0.7.0"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/termimad"
description = "Markdown Renderer for the Terminal"
edition = "2018"
keywords = ["markdown", "terminal", "tui", "renderer", "parser"]
license = "MIT"
categories = ["command-line-interface", "text-processing"]
readme = "README.md"

[dependencies]
lazy_static = "1.3"
minimad = "0.4.1"
crossterm = "0.12.1"
crossbeam = "0.7"
thiserror = "1.0.2"

[patch.crates-io]
crossterm = { path = "../crossterm-rs/crossterm" }
